version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laraapp_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      args:
        user: camila #utilizar o mesmo usuário do WSL
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
      - 8000:8000
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
